#!/usr/bin/env ruby

# Open the GitHub pull request for the current branch.
#
# `git openpr`
#
# Usage:
#
# 1. Set your `GITHUB_OAUTH_REPO_TOKEN` environment variable.
# 2. Install Bundler, e.g. `gem install bundler`.
# 3. Put this script on your path, and make it executable.
# 4. Call `git openpr`.
# 5. Be amazed.
#
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'octokit', '~> 4.3'
  gem 'git', '~> 1.5'
end

git = Git.open('.')
current_branch = git.current_branch
origin = git.remotes.find { |remote| remote.name == 'origin' }

match_data = origin.url.match(/git@github.com:(.*)\/(.*)\.git/)
organization, repo_name = match_data.captures

organization, repo_name = origin.url.match(/git@github.com:(.*)\/(.*)\.git/).captures
repo_full_name = "#{organization}/#{repo_name}"

access_token = ENV['GITHUB_OAUTH_REPO_TOKEN'] || abort("GITHUB_OAUTH_REPO_TOKEN isn't defined")
client = Octokit::Client.new(:access_token => access_token)
pull_requests = client.pull_requests(repo_full_name, head: "#{organization}:#{current_branch}")

pull_request_html_url = pull_requests.first&.html_url || "https://github.com/#{repo_full_name}/compare/master...#{current_branch}"

puts pull_request_html_url
`open #{pull_request_html_url}`
